export const neighborhoods = [
  'Rogers Park',
  'West Ridge',
  'Uptown',
  'Lincoln Square',
  'North Center',
  'Lake View',
  'Lincoln Park',
  'Near North Side',
  'Edison Park',
  'Norwood Park',
  'Jefferson Park',
  'Forest Glen',
  'North Park',
  'Albany Park',
  'Portage Park',
  'Irving Park',
  'Dunning',
  'Montclare',
  'Belmont Cragin',
  'Hermosa',
  'Avondale',
  'Logan Square',
  'Humboldt Park',
  'West Town',
  'Austin',
  'West Garfield Park',
  'East Garfield Park',
  'Near West Side',
  'North Lawndale',
  'South Lawndale',
  'Lower West Side',
  'The Loop',
  'Near South Side',
  'Armour Square',
  'Douglas',
  'Oakland',
  'Fuller Park',
  'Grand Boulevard',
  'Kenwood',
  'Washington Park',
  'Hyde Park',
  'Woodlawn',
  'South Shore',
  'Chatham',
  'Avalon Park',
  'South Chicago',
  'Burnside',
  'Calumet Heights',
  'Roseland',
  'Pullman',
  'South Deering',
  'East Side',
  'West Pullman',
  'Riverdale',
  'Hegewisch',
  'Garfield Ridge',
  'Archer Heights',
  'Brighton Park',
  'McKinley Park',
  'Bridgeport',
  'New City',
  'West Elsdon',
  'Gage Park',
  'Clearing',
  'West Lawn',
  'Chicago Lawn',
  'West Englewood',
  'Englewood',
  'Greater Grand Crossing',
  'Ashburn',
  'Auburn Gresham',
  'Beverly',
  'Washington Heights',
  'Mount Greenwood',
  'Morgan Park',
  "O'Hare",
  'Edgewater'
];
