import {
  ProductionEquity,
  ProductionStatus,
  ProductionType
} from '../components/Profile/shared/profile.types';
import { getOptionsFromEnum } from './helpers';

export const neighborhoods = [
  'Albany Park',
  'Archer Heights',
  'Armour Square',
  'Ashburn',
  'Auburn Gresham',
  'Austin',
  'Avalon Park',
  'Avondale',
  'Belmont Cragin',
  'Beverly',
  'Bridgeport',
  'Brighton Park',
  'Burnside',
  'Calumet Heights',
  'Chatham',
  'Chicago Lawn',
  'Clearing',
  'Douglas',
  'Dunning',
  'East Garfield Park',
  'East Side',
  'Edgewater',
  'Edison Park',
  'Englewood',
  'Forest Glen',
  'Fuller Park',
  'Gage Park',
  'Garfield Ridge',
  'Grand Boulevard',
  'Greater Grand Crossing',
  'Hegewisch',
  'Hermosa',
  'Humboldt Park',
  'Hyde Park',
  'Irving Park',
  'Jefferson Park',
  'Kenwood',
  'Lake View',
  'Lincoln Park',
  'Lincoln Square',
  'Logan Square',
  'Lower West Side',
  'McKinley Park',
  'Montclare',
  'Morgan Park',
  'Mount Greenwood',
  'Near North Side',
  'Near South Side',
  'Near West Side',
  'New City',
  'North Center',
  'North Lawndale',
  'North Park',
  'Norwood Park',
  'Oakland',
  'Portage Park',
  'Pullman',
  'Riverdale',
  'Rogers Park',
  'Roseland',
  'South Chicago',
  'South Deering',
  'South Lawndale',
  'South Shore',
  'The Loop',
  'Uptown',
  'Washington Heights',
  'Washington Park',
  'West Elsdon',
  'West Englewood',
  'West Garfield Park',
  'West Lawn',
  'West Pullman',
  'West Ridge',
  'West Town',
  'Woodlawn',
  "O'Hare"
];
